apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-backend
  labels:
    app: {{ include "myapp.name" . }}
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MONGO_URI
              value: "{{ .Values.backend.env.MONGO_URI }}"
