apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.frontend.port }}
      - name: backend
        image: {{ .Values.backend.image }}
        
        imagePullPolicy: Always
        env:
          - name: MONGO_URI
            value: {{ .Values.mongoUri }}
        ports:
          - containerPort: {{ .Values.backend.port }}
