apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-frontend-svc
  labels:
    app: {{ include "myapp.name" . }}
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "myapp.name" . }}
    tier: frontend
